### ISSUE TITLE
How jeremykenedy/laravel-uuid be unique world wide

### ISSUE THREAD

**Issue by saifuldhaka** [jeremykenedy/laravel-uuid#2]
hi i used jeremykenedy/laravel-uuid in my laravel5.4 project. i want to get unique id for non registered members to track their activities. but Uuid::generate(5,'test', Uuid::NS_DNS) generates same id of my different testing pc. have any idea can make the unique identifier machine based for each end user. thanks

**Comment by jeremykenedy** [comment]
`Uuid::generate(5,'test', Uuid::NS_DNS)` should generate a unique UUID but not that the UUID is based on the NS_DNS variable may end up being the same because of the value it's based on.

You can try `Uuid::generate(4)` to generate a truly random UUID.

**Comment by saifuldhaka** [comment]
check here 
http://dev.shopavision.com/uid
user: client
pass: ocg!@#$

from my pc i got this id: **4be0643f-1d98-573b-97cd-ca98a65347dd**

**Comment by saifuldhaka** [comment]
Uuid::generate(4) each time it generate different id for me. actually i want a unique id, like it will be fixed unique for me, different id for you and always same until you not use different pc. thanks

**Comment by saifuldhaka** [comment]
actually i want an id like, when i visit my site it will generate an id for me and this id will me always same when i back next time again. like a registered member.
